### ISSUE TITLE
Ui.Tab is not working

### ISSUE THREAD

**Issue by istvan-andrasi** [mint-lang/mint-ui#33]
Hi!

I'm getting familiar with mint and mint-ui, and as a first step I read through the docs/examples.
I noticed that Ui.Tab is not working on https://ui.mint-lang.com/documentation/tabs, when I click the other tab the content remains the same. I tried it out locally (checked with the develop branch as well) and got the same result.

I haven't looked into it, but I thought I'd point it out.
Keep up the good work!

**Comment by gdotdesign** [comment]
Hi :wave: 

Thanks for opening this issue! All components are controlled, meaning you need a place to store the state of the component. On that page, the tab state is not wired in, so that's why it's not changing. You can check out the reference of the `Ui.Tabs` for a working version https://ui.mint-lang.com/components/ui-tabs (source https://github.com/mint-lang/mint-ui-website/blob/master/source/Reference/Tabs.mint)

**Comment by istvan-andrasi** [comment]
Ah, OK, thanks!
